In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/blair-developer/dataMain/refs/heads/main/Walmart_Sales.csv')
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

**1. Identify missing data and eliminate duplicate entries in the dataset**

In [ ]:
#check for missing value
df.isnull().sum()#there is no missing values

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
dtype: int64

In [ ]:
#eliminate duplicates
#first check for duplicates
df.duplicated().sum()

np.int64(0)

result show there is no duplicate but if there were we would remove duplicates using.drop duplicates
#df = df.drop_duplicates()

**2. Transform the Date column into a Pandas datetime object.**

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106

**3. Add a new column called Revenue, calculated as the product of Weekly_Sales and a hypothetical Fuel_Price column.**

In [ ]:
#Add a new column called Revenue
df['Revenue'] = df['Weekly_Sales'] * df['Fuel_Price']
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Revenue
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,4.227573e+06
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,4.183708e+06
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,4.052488e+06
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,3.610312e+06
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,4.081368e+06

**4. Identify and handle Garbage values**

In [ ]:
df.isnull().sum()#checking for null values

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
Revenue         0
dtype: int64

In [ ]:
df.duplicated().sum()#checking for duplicates

np.int64(0)

**5. Standardize the categorical column `holiday_flag` by mapping the values 0 and 1 to "No Holiday" and "Holiday," respectively.**

In [ ]:
# Standardize the 'holiday_flag' column
df['Holiday_Flag'] = df['Holiday_Flag'].map({0: 'No Holiday', 1: 'Holiday'})
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Revenue
0,1,2010-02-05,1643690.90,No Holiday,42.31,2.572,211.096358,8.106,4.227573e+06
1,1,2010-02-12,1641957.44,Holiday,38.51,2.548,211.242170,8.106,4.183708e+06
2,1,2010-02-19,1611968.17,No Holiday,39.93,2.514,211.289143,8.106,4.052488e+06
3,1,2010-02-26,1409727.59,No Holiday,46.63,2.561,211.319643,8.106,3.610312e+06
4,1,2010-03-05,1554806.68,No Holiday,46.50,2.625,211.350143,8.106,4.081368e+06

**6.Identify any outliers present in the dataset and highlight the rows containing them.**

In [ ]:
df[['Weekly_Sales','Temperature','Fuel_Price','CPI',"Revenue"]].skew()

Weekly_Sales    0.668362
Temperature    -0.336768
Fuel_Price     -0.096158
CPI             0.063492
Revenue         0.697142
dtype: float64

In [ ]:
df[['Weekly_Sales','Temperature','Fuel_Price','CPI',"Revenue"]].kurtosis()

Weekly_Sales    0.053141
Temperature    -0.612801
Fuel_Price     -1.177378
CPI            -1.839813
Revenue        -0.073543
dtype: float64